version: "3"

services:
    app:
        image: csv_transformer:latest
        deploy:
            replicas: 5
            resources:
                limits:
                    cpus: "0.1"
                    memory: "50M"
            restart_policy:
                condition: on-failure
        ports:
            - "80:8000"
        networks:
            - webnet
networks:
    webnet:
